<?php

/**
 * @file
 * Contains osm.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function osm_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the osm module.
    case 'help.page.osm':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Open Street Map Custom Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function osm_theme() {
  return [
    'osm' => [
      'render element' => 'children',
    ],
  ];
}
